### ISSUE TITLE
Bug in proxy-state-tree: Adding a object reference through Object.defineProperty(...., get:()) in action doesn't work

### ISSUE THREAD

**Issue by Jimmy89** [cerebral/overmind#343] opened 2019-12-11 15:31 UTC
Hello all,

Update with specifics on the bug are on the bottom of this issue.

I have the following issue which I'm stuck at. I have the following action
```
  addAjacent({ state }, { sourceNodeUuid, destinationNodeUuid }) {
    if (state.graph[sourceNodeUuid] && state.graph[destinationNodeUuid]) {
      Object.defineProperty(state.graph[sourceNodeUuid].adjacents, destinationNodeUuid, {
        // Ensure we can remove the reference if we want to.
        configurable: true,
        /** Place a general getter on the uuid
         *  @see https://overmindjs.org/guides/beginner/02_definingstate?view=react&typescript=false#defining-state-references
         *  @return {object} node Destination node that is being attached to the source node.
         */
        get() {
          return state.graph[destinationNodeUuid];
        }
      });
    }
  },
```

I'm building a simple graph where nodes can be linked to each other. 

My state is:
```
const state = {
  graph: {
    "2c5ea4c0-4067-11e9-8bad-9b1deb4d3b7d": {
      type: "specialElement",
      adjacents: {
        get "c94bf7e6-5462-4598-91fb-e2430560ff7e"() {
          return state.graph["99b7efc0-2dc0-4a2d-b130-796a6506dfba"];
        }
      }
    },
    "99b7efc0-2dc0-4a2d-b130-796a6506dfba": {
      type: "anyOf",
      adjacents: {}
    },
} 
}
```

The idea is that graph objects can be linked to each other without duplicating objects. Based on the overmind information [https://overmindjs.org/guides/beginner/02_definingstate?view=react&typescript=false#defining-state-references](Overmind link) I used Object.defineProperty to generate a getter, so I would replicate the following lines dynamically:

```
        get "c94bf7e6-5462-4598-91fb-e2430560ff7e"() {
          return state.graph["99b7efc0-2dc0-4a2d-b130-796a6506dfba"];
        }
```

However, the end result is that the generated getter is not in state when I request it. I tried out the code on plain JS objects and that worked, so I'm wondering whether I'm using it correctly for overmind.

Anyone got any clue?

Update: I found that the defineProperty handler is not trapped in the ObjectProxy on [https://github.com/cerebral/overmind/blob/next/packages/node_modules/proxy-state-tree/src/Proxyfier.ts#L265](Code link). Therefore, when the object is being read that contains the newly set getter, the value is being returned from a cached proxy that does not have the newly defined Property because the methods of the MutationTree hasn't been updated. However, calling the getter directly provides the result, because the get handler handles getters differently (returns the value directly).

```
    test("get() bug in proxy-state-tree", () => {
      const overmind = createOvermindMock(config, { });

      overmind.actions.addAjacent({ sourceNodeUuid: "2c5ea4c0-4067-11e9-8bad-9b1deb4d3b7d", destinationNodeUuid: "7bf45639-0845-4ee6-8ef6-cfc8a74b0308" });

      expect(overmind.state.graph["2c5ea4c0-4067-11e9-8bad-9b1deb4d3b7d"].adjacents["7bf45639-0845-4ee6-8ef6-cfc8a74b0308"]).toBeDefined(); <--- This works, because the value is retrieved from the Object itself
      expect(overmind.state.graph["2c5ea4c0-4067-11e9-8bad-9b1deb4d3b7d"].adjacents).toHaveLength(2); <-- This is 1, instead of 2, because the MutationTree with an old view of the Object exists.
    });

**Comment by christianalfoni** [comment] 2020-06-07 14:52
Hi @Jimmy89 and sorry for late reply here,

Thanks for explaining the issue and this is added to bug list!

**Comment by christianalfoni** [comment] 2020-09-05 15:57
Hi @Jimmy89 ,

Okay, so I looked more closely at this. So yeah, the issue is that you scope your getter to the scope of the action when it is created. I am a bit unsure why this "old proxy" appears, but a bigger issue is that you are returning "action mutation state" from something that is meant to be "component tracking state". So you might get into more issues here.

What I would rather do here is create derived.

So instead of:

```ts
  addAjacent({ state }, { sourceNodeUuid, destinationNodeUuid }) {
    if (state.graph[sourceNodeUuid] && state.graph[destinationNodeUuid]) {
      Object.defineProperty(state.graph[sourceNodeUuid].adjacents, destinationNodeUuid, {
        // Ensure we can remove the reference if we want to.
        configurable: true,
        /** Place a general getter on the uuid
         *  @see https://overmindjs.org/guides/beginner/02_definingstate?view=react&typescript=false#defining-state-references
         *  @return {object} node Destination node that is being attached to the source node.
         */
        get() {
          return state.graph[destinationNodeUuid];
        }
      });
    }
  },
```

I would write:

```ts
  addAjacent({ state }, { sourceNodeUuid, destinationNodeUuid }) {
    if (state.graph[sourceNodeUuid] && state.graph[destinationNodeUuid]) {
      state.graph[sourceNodeUuid].adjacents[destinationNodeUuid] = derived((_, rootState) => {
        return rootState.graph[destinationNodeUuid]
      })
    }
  },
```

This should properly deal with everything. You import `derived` from the overmind package.

**Comment by christianalfoni** [comment] 2021-01-09 09:47
Closing this, please reopen if still issue

**Closed by christianalfoni** 2021-01-09 09:47 UTC
Labels: question
