### ISSUE TITLE
Lazy.loadConfig does not return loading promise! 

### ISSUE THREAD

**Issue by JeronimoBlack** [cerebral/overmind#283] opened 2019-06-15 18:11 UTC
There for is not possible to load a lazy module and call an action, effect or access it's state! 

Ex.:
await actions.lazy.loadConfig("aLazyModule") ;
actions.aLazyModule.doSomething() ;

**Comment by christianalfoni** [comment] 2019-06-22 17:10
Hi there and thanks for reporting!

There are tests written for this, though it is not a common feature. What kind of error are you receiving? If you could create a codesandbox example that would be even awesomer :)

Will nevertheless look into this before next release :)

**Comment by christianalfoni** [comment] 2019-06-27 17:05
Hm, I looked at this and not able to reproduce. I also added an action execution to the test, just to make sure. Would be great with a Codesandbox example to help you out on this one :)

**Comment by JeronimoBlack** [comment] 2019-06-28 08:25
Here is the test project:

**Comment by christianalfoni** [comment] 2019-06-28 09:01
Aha! I see now, I will look into this ASAP. We have a pending release and will make sure this is part of it :)

**Comment by christianalfoni** [comment] 2019-06-29 12:57
Okay, @JeronimoBlack , if you install `npm install overmind@next and overmind-react@next` things should work as expected :)

Thanks a bunch for reporting this as this was clearly not working as intended!

**Comment by christianalfoni** [comment] 2019-07-10 11:24
Closing this as the fix was part of the previous release :)

**Closed by christianalfoni** 2019-07-10 11:24 UTC
