### ISSUE TITLE
Actions not passed to connected component on server.

### ISSUE THREAD

**Issue by vinceprofeta** [cerebral/overmind#248] opened 2019-03-19 14:57 UTC
I am not sure if this is done by design, but having the app setup as instructed in the `structuring your app` and `server rendering` sections of the guide my app on the server breaks. I am getting and error cannot real modals of undefined error when trying to access `actions.modals.openModal` in an onClick handler. 

const { actions } = useOvermind();
In render
```
return (
  <div  onClick={actions.sidebars.toggleDrawer}></div>
)
```

I could set actions to a default {} but wanted to make sure I wasn't doing anything wrong.

Huge fan of this library coming from Baobab and Celebral! Great Work!

**Comment by christianalfoni** [comment] 2019-04-25 18:27
@vinceprofeta Hi there!

By design the actions are not exposed on the server, but I certainly see your issue. The idea is really not for the actions to be called, but you are of course just referencing them. This should certainly be fixed. We can expose mocked actions instead :)

Noted!

**Comment by luisherranz** [comment] 2019-04-26 07:57
I'd like to ask a related question.

This is your example of SSR:
```js
const overmind = createOvermindSSR(config)

overmind.state.currentPage = 'posts'
overmind.state.posts = await db.getPosts()
```

What's the point of forbidding actions to be called in the server? You are forcing people to reimplement the logic they probably already have inside actions just to be used in the server.

In your example that would be:
```js
const overmind = createOvermindSSR(config)

overmind.actions.setCurrentPage('posts');
overmind.actions.fetchPosts();
```

Here it may seem trivial but I can imagine much more complex actions than just two lines of code.

**Comment by christianalfoni** [comment] 2019-05-12 11:38
@luisherranz 

Yeah, good question :) It is really about how implicit you want to be. Cause somewhere there has to be one piece of code that creates a request to an API endpoint and one piece of code creating a request to a database. The question is where you want that code to live and how explicit you want to be. Like if both client and server uses a `fetcPosts` action the logic of being on the client/server has to either be inside the action or even the action could call `effects.data.getPosts`, where the effect checked the environment to do an API endpoint request or a database request. 

Personally I think this becomes too implicit. I like to think of my app as a client app and my server as a different app. What `createOvermindSSR` really does is just give you a tool to expose state when you render your components on the server. 

That said! I do not want to say it is a bad idea to do what you are suggesting and you can actually do it. You can use the `createOvermind` factory as well on the server and explore this. I was a bit worried about memory leaks, but this has been tested and it seems to run just fine.

So yeah, when someone has an example of this running I am happy to put a guide on the website :)

**Comment by christianalfoni** [comment] 2019-05-12 13:54
@vinceprofeta Hm... I looked more into this now. I do not see any reason for it to not work? I was wrong, we are indeed exposing the actions. 

but you mention that you have an onClick handler where you try to access `actions.modals.openModal`... are you sure it exists? Could you try logging out the actions object? Cause you should have actions there. 

Oh... maybe you are not exposing Overmind to the app? Make sure you use the `Provider` so that Overmind is actually accessible in the component. 

```ts
  const html = renderToString(
    <Provider value={overmind}>
      <App />
    </Provider>
  )
```

**Comment by christianalfoni** [comment] 2019-06-15 13:56
Closing this for now :) Please reopen if still issue

**Comment by suevalov** [comment] 2019-12-03 11:59
Hi @christianalfoni! I've stumbled upon with this limitation as well and I don't see any reasons why the actions should not be available in SSR version. 

Basically we should be able to render the application on a server and hydrate all mutations at the end of the render without any limitations.

Something like this: https://github.com/zeit/next.js/tree/canary/examples/with-mobx-state-tree-typescript

**Comment by christianalfoni** [comment] 2019-12-30 16:31
@suevalov Hi there!

Yeah, totally agree, though I do not see why it is not working? Do you have an example? I do not see in the code why the actions are not there.

**Comment by marbemac** [comment] 2020-01-07 21:38
Hi @christianalfoni - just getting started with Overmind, and loving it so far! Here's a reproducible example: https://github.com/marbemac/overmind-ssr-actions-bug

BTW double you'll remember, but we met over a call ~5-6 years ago when you were getting started with Cerebral :).

**Comment by marbemac** [comment] 2020-01-11 20:37
Figured I'd drop some notes as I continue to add Overmind to our project. Here are a couple of react patterns that are not possible due to actions being undefined in  SSR:

```tsx
<Card onClick={actions.projects.loadNextPage}>Next</Card>

// Have to wrap it or use useCallback so it's not accessed in SSR
<Card onClick={() => actions.projects.loadNextPage()}>Next</Card>
```

Have to add eslint ignore's everywhere so that the react-hooks rules don't add the used action to the hook dependencies array:

```tsx
React.useEffect(() => {
  actions.workspaces.setCurrentWorkspaceId(workspaceId);
}, [actions.workspaces, workspaceId]);

// have to add ignore comment and remove from dependencies

React.useEffect(() => {
  actions.workspaces.setCurrentWorkspaceId(workspaceId);
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [workspaceId]);
```

**Comment by christianalfoni** [comment] 2020-01-20 17:20
Hi @marbemac , sorry for late reply here! :)

I do remember you, well, I remember your avatar image!

Just stupid that this has taken so long, cause it was just moving a line in the code. If you want to try "@next" now: `npm install overmind@next overmind-react@next`, it should work 👍 😄 

Build: https://travis-ci.org/cerebral/overmind/builds/639580542

**Comment by marbemac** [comment] 2020-01-23 02:59
Ah yes, this image is getting quite old ha :).

Verified work as expected, good work! 👍

**Comment by marbemac** [comment] 2020-01-23 06:44
Related question that couldn't find answer for in docs - is `onInitialize` supposed to run in SSR? Right not it does not seem to, which is kind of problematic if there is any state setup (like making some API calls to fetch initial data, etc), since that state will not be present when client app starts up. Thoughts? Happy to open separate issue if this is valid.

**Comment by christianalfoni** [comment] 2020-01-23 11:24
Ah, yeah, no it does not fire up. The reason is that it is considered a side effect on the server that you might not want. Like with tests, you do not want onInitialize to fire up as it would cause a side effect to your tests.

But what I suggest you do here is to rather create your own action an do:

```js
const onInitialize = ({ actions }) => actions.isomorphicOnInitialize()
```

Now you can call this action manually when on the server :)

Or just manually call it on the client as well:

```js
const overmind = createOvermind(config)
overmind.actions.isomorphicOnInitialize()
```

I will write about it in the docs :)

**Closed by christianalfoni** 2020-01-23 11:24 UTC
